ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = sdsc-qe
VERSION        = 6.4.1
RELEASE        = 1
PKGROOT        = /opt/qe

SRC_SUBDIR     = qe

SOURCE_NAME    = q-e-qe
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

EXAMPLE_SOURCE_VERSION = 6.0
EXAMPLE_SOURCE_NAME    = qe-$(EXAMPLE_SOURCE_VERSION)-examples
EXAMPLE_SOURCE_SUFFIX  = tar.gz
EXAMPLE_SOURCE_PKG     = $(EXAMPLE_SOURCE_NAME).$(EXAMPLE_SOURCE_SUFFIX)
EXAMPLE_SOURCE_DIR     = Examples

TAR_GZ_PKGS    = $(SOURCE_PKG) $(EXAMPLE_SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No\nAutoProv:No\nObsoletes: qe
RPM.PREFIX     = $(PKGROOT)
