ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = qe
VERSION        = 5.1
RELEASE        = 4
PKGROOT        = /opt/qe

SRC_SUBDIR     = qe

SOURCE_NAME    = espresso
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

ATOMIC_NAME    = atomic
ATOMIC_SUFFIX  = tar.gz
ATOMIC_VERSION = 5.1
ATOMIC_PKG     = $(ATOMIC_NAME)-$(ATOMIC_VERSION).$(ATOMIC_SUFFIX)
ATOMIC_DIR     = atomic

NEB_NAME       = neb
NEB_SUFFIX     = tar.gz
NEB_VERSION    = 5.1
NEB_PKG        = $(NEB_NAME)-$(NEB_VERSION).$(NEB_SUFFIX)
NEB_DIR        = NEB

PHONON_NAME    = PHonon
PHONON_SUFFIX  = tar.gz
PHONON_VERSION = 5.1
PHONON_PKG     = $(PHONON_NAME)-$(PHONON_VERSION).$(PHONON_SUFFIX)
PHONON_DIR     = PHonon

PWCOND_NAME    = pwcond
PWCOND_SUFFIX  = tar.gz
PWCOND_VERSION = 5.1
PWCOND_PKG     = $(PWCOND_NAME)-$(PWCOND_VERSION).$(PWCOND_SUFFIX)
PWCOND_DIR     = PWCOND

TDDFPT_NAME    = tddfpt
TDDFPT_SUFFIX  = tar.gz
TDDFPT_VERSION = 5.1
TDDFPT_PKG     = $(TDDFPT_NAME)-$(TDDFPT_VERSION).$(TDDFPT_SUFFIX)
TDDFPT_DIR     = TDDFPT

XSPECTRA_NAME    = xspectra
XSPECTRA_SUFFIX  = tar.gz
XSPECTRA_VERSION = 5.1
XSPECTRA_PKG     = $(XSPECTRA_NAME)-$(XSPECTRA_VERSION).$(XSPECTRA_SUFFIX)
XSPECTRA_DIR     = XSpectra

TAR_GZ_PKGS    = \
  $(SOURCE_PKG) $(ATOMIC_PKG) $(NEB_PKG) $(PHONON_PKG) $(PWCOND_PKG) \
  $(TDDFPT_PKG) $(XSPECTRA_PKG)

RPM.EXTRAS     = AutoReq:No
